apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    # Original Helm labels v
    app: {{ template "connector.name" . }}
    component: cron-connector
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    # Helm/k8s recommended label names v
    app.kubernetes.io/name: {{ template "connector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: cron-connector
    app.kubernetes.io/part-of: openfaas
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "connector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "connector.name" . }}
      app.kubernetes.io/component: cron-connector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "connector.name" . }}
        app.kubernetes.io/component: cron-connector
    spec:
      containers:
      - name: cron-connector
        image: {{ .Values.image }}
        env:
          - name: gateway_url
            value: {{ .Values.gateway_url | quote }}
          {{- if .Values.basic_auth }}
          - name: basic_auth
            value: "true"
          - name: secret_mount_path
            value: "/var/secrets"
          {{- end }}
        {{- if .Values.basic_auth }}          
        volumeMounts:
            - name: auth
              readOnly: true
              mountPath: "/var/secrets/"
        {{- end }}
      {{- if .Values.basic_auth }}
      volumes:
      - name: auth
        secret:
          secretName: basic-auth
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
